name: part
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.22.0
  - ca-certificates=2026.1.4
  - gflags=2.2.2
  - glog=0.7.1
  - hdf5=1.14.6
  - icu=73.2
  - krb5=1.21.3
  - libabseil=20250512.1
  - libaec=1.1.5
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - liblapack=3.11.0
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - numexpr=2.14.1
  - openssl=3.6.0
  - orc=2.2.2
  - packaging=25.0
  - pip=25.3
  - prometheus-cpp=1.3.0
  - py-cpuinfo=9.0.0
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pytables=3.10.2
  - python=3.13.11
  - python_abi=3.13
  - re2=2025.11.05
  - readline=8.3
  - setuptools=80.10.1
  - snappy=1.2.2
  - sqlite=3.51.1
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - awkward==2.8.12
      - awkward-cpp==51
      - awkward0==0.15.5
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lz4==4.4.5
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==1.26.4
      - pandas==3.0.0
      - pillow==12.1.0
      - protobuf==6.33.4
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.10.0
      - tqdm==4.67.1
      - uproot==5.1.2
      - urllib3==2.6.3
      - vector==1.7.0
      - weaver-core==0.4.17
      - werkzeug==3.1.5
      - xxhash==3.6.0
prefix: /opt/miniconda3/envs/part
