name: part
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h54b0cfc_0
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - blosc=1.21.6=h7dd00d9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.22.0=hb83781b_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - hdf5=1.14.6=nompi_h51e7c0a_105
  - icu=73.2=hc8870d7_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.5=h8664d51_0
  - libarrow=22.0.0=h8df5332_8_cpu
  - libarrow-acero=22.0.0=hb3c16fa_8_cpu
  - libarrow-compute=22.0.0=hca5012c_8_cpu
  - libarrow-dataset=22.0.0=hb3c16fa_8_cpu
  - libarrow-substrait=22.0.0=h49b2eaa_8_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.18.0=he38603e_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h8d60b75_8_cpu
  - libprotobuf=6.31.1=h98f38fd_4
  - libre2-11=2025.11.05=h91c62da_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libutf8proc=2.11.3=h2431656_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - ncurses=6.5=hee39554_0
  - nlohmann_json=3.12.0=h784d473_1
  - numexpr=2.14.1=py313h73ed539_1
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.2=hac85105_0
  - packaging=25.0=py313hca03da5_1
  - pip=25.3=pyhc872135_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313h39782a4_1
  - pyarrow-core=22.0.0=py313hcc89289_1_cpu
  - pytables=3.10.2=py313h5ba8fac_10
  - python=3.13.11=hc7d8306_100_cp313
  - python_abi=3.13=3_cp313
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py313hca03da5_0
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - absl-py==2.3.1
      - awkward==2.8.12
      - awkward-cpp==51
      - awkward0==0.15.5
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lz4==4.4.5
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==1.26.4
      - pandas==3.0.0
      - pillow==12.1.0
      - protobuf==6.33.4
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.10.0
      - tqdm==4.67.1
      - uproot==5.1.2
      - urllib3==2.6.3
      - vector==1.7.0
      - weaver-core==0.4.17
      - werkzeug==3.1.5
      - xxhash==3.6.0
prefix: /opt/miniconda3/envs/part
